name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/img/foto.png
    - lib/img/briefcase-and-tools-for-school 1.png
    - lib/img/cutlery (1) 1.png
    - lib/img/dormitory 1.png
