// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrXuC0UK3fxZw1Yhn-8J-CM0N_gSSLfMU',
    appId: '1:840803479272:web:b065ea738c35beb7c3e35d',
    messagingSenderId: '840803479272',
    projectId: 'aplikasi-kos-489fa',
    authDomain: 'aplikasi-kos-489fa.firebaseapp.com',
    storageBucket: 'aplikasi-kos-489fa.firebasestorage.app',
    measurementId: 'G-NZ1YJ06SSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9p9zsooXHZseYuIrYKHU1IPNGsAJrrHY',
    appId: '1:840803479272:android:335d2c61eb837911c3e35d',
    messagingSenderId: '840803479272',
    projectId: 'aplikasi-kos-489fa',
    storageBucket: 'aplikasi-kos-489fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7RRnPQNVwTkSJT2LXhUUeWnCrIOZ9wKc',
    appId: '1:840803479272:ios:32570c2eb7becb0bc3e35d',
    messagingSenderId: '840803479272',
    projectId: 'aplikasi-kos-489fa',
    storageBucket: 'aplikasi-kos-489fa.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7RRnPQNVwTkSJT2LXhUUeWnCrIOZ9wKc',
    appId: '1:840803479272:ios:32570c2eb7becb0bc3e35d',
    messagingSenderId: '840803479272',
    projectId: 'aplikasi-kos-489fa',
    storageBucket: 'aplikasi-kos-489fa.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
